"""initial_schema

Revision ID: bff4d118bed5
Revises: 
Create Date: 2026-04-10 17:56:55.234091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bff4d118bed5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('known_plugins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('monthly_cost_low', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('monthly_cost_high', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('detection_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_known_plugins_slug'), 'known_plugins', ['slug'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('store_url', sa.String(length=2048), nullable=False),
    sa.Column('monthly_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_traffic', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pages_discovered', sa.Integer(), nullable=True),
    sa.Column('avg_load_time_ms', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('estimated_monthly_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_plugin_cost_monthly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detected_plugins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('estimated_monthly_cost', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('detection_method', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detected_plugins')
    op.drop_table('reports')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_known_plugins_slug'), table_name='known_plugins')
    op.drop_table('known_plugins')
    # ### end Alembic commands ###
